Login signup
chibukasia/online-charity-management-system pull request #14
Opened 2022-10-22 13:08 UTC by Tkamunya1

Authentication still not through

2022-10-22 14:10 UTC, chibukasia requested changes
Please add the comments as well and check the review comments. Also, let me know if you used the react-bootstrap stylings in the styles folder. I may not be familiar with them and I just can't merge something I don't understand. Finally, let commmit and push small chunks of codes. Work on a component, commit and push and lets review it. These has a lot of lines of code to review

2022-10-22 14:10 UTC, chibukasia commented on client/src/components/LoginForm.js
> +        r.json().then((user) => onLogin(user));
We need to redirect a user to different page based on their roles

2022-10-22 14:10 UTC, chibukasia commented on client/src/components/SignUpForm.js
> +  const [password, setPassword] = useState("");
You missed adding the email. Please consider adding an email field and useSate

2022-10-22 14:10 UTC, chibukasia commented on client/src/components/SignUpForm.js
> +        phone_number,
email is missing

2022-10-22 14:10 UTC, chibukasia commented on client/src/components/SignUpForm.js
> +        r.json().then((user) => onLogin(user));
We need to redirect the user after sign up to the appropriate page based on the role. We'll help you with that

2022-10-22 14:10 UTC, chibukasia commented on client/src/components/SignUpForm.js
> +          autoComplete="off"
include the html name attribute as I had told you earlier

2022-10-22 14:10 UTC, chibukasia commented on client/src/components/SignUpForm.js
> +          id="last_name"
html name attribute is missing

2022-10-22 14:10 UTC, chibukasia commented on client/src/components/SignUpForm.js
> +        />
Add email input field as well

2022-10-23 07:33 UTC, munenebrian reviewed
I think other than the few pointers from chebukasia, i think it's job well done.

2022-10-23 10:01 UTC, munenebrian reviewed
I think other than the few pointers from chebukasia, i think it's job well done.

2022-10-24 06:43 UTC, chibukasia approved these changes

2022-10-24 06:44 UTC, merged